# Generated by Django 4.2 on 2024-05-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='description',
            field=models.TextField(default='descripcion por defecto'),
        ),
        migrations.AddField(
            model_name='flan',
            name='name',
            field=models.CharField(default='nombre por defecto', max_length=50),
        ),
        migrations.AddField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
